
export const user = {
  LOGIN: 'LOGIN',
  LOAD_LOCAL_USERINFO: 'LOAD_LOCAL_USERINFO',
  SIGN_OUT: 'SIGN_OUT'

}

export const notification = {
  NOTIFICATION_LIST: 'NOTIFICATION_LIST',
  NOTIFICATION_DETAIL: 'NOTIFICATION_DETAIL'
}
